### ISSUE TITLE
cxd2843 does not see to work 

### ISSUE THREAD

**Issue by cbtrident** [flensrocker/dddvb#1]
have try you driver and even thought i can install and detect the 2837 chip
it will scan using w_scan but it not detecting any channels
not sure why it not working any idea on how i can debug and find what wrong

thanks
Carl

**Comment by cbtrident** [comment]
forgot to say dvb-t and dvb-t2 not working for me dont know about dvb-c as i dont have access to that

**Comment by flensrocker** [comment]
I'm sorry, I don't have hardware for cxd2843. The official repository of this driver package is here:
https://github.com/DigitalDevices/dddvb

I just maintain a dkms-package for Ubuntu based installations. I don't work on the driver.
